// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventValue.proto

package tw.com.wd.proto;

public interface EventValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:entity.EventValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();

  /**
   * <code>int64 eventTimestamp = 2;</code>
   * @return The eventTimestamp.
   */
  long getEventTimestamp();

  /**
   * <code>string receiverId = 3;</code>
   * @return The receiverId.
   */
  String getReceiverId();
  /**
   * <code>string receiverId = 3;</code>
   * @return The bytes for receiverId.
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string giverId = 4;</code>
   * @return The giverId.
   */
  String getGiverId();
  /**
   * <code>string giverId = 4;</code>
   * @return The bytes for giverId.
   */
  com.google.protobuf.ByteString
      getGiverIdBytes();

  /**
   * <code>.entity.EventValue.EventType eventType = 5;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.entity.EventValue.EventType eventType = 5;</code>
   * @return The eventType.
   */
  EventValue.EventType getEventType();

  /**
   * <code>.entity.EventValue.EventSource eventSource = 6;</code>
   * @return The enum numeric value on the wire for eventSource.
   */
  int getEventSourceValue();
  /**
   * <code>.entity.EventValue.EventSource eventSource = 6;</code>
   * @return The eventSource.
   */
  EventValue.EventSource getEventSource();
}
