// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventValue.proto

package tw.com.wd.proto;

public final class EventValueOuterClass {
  private EventValueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_entity_EventValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_entity_EventValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020EventValue.proto\022\006entity\"\317\002\n\nEventValu" +
      "e\022\r\n\005value\030\001 \001(\005\022\026\n\016eventTimestamp\030\002 \001(\003" +
      "\022\022\n\nreceiverId\030\003 \001(\t\022\017\n\007giverId\030\004 \001(\t\022/\n" +
      "\teventType\030\005 \001(\0162\034.entity.EventValue.Eve" +
      "ntType\0223\n\013eventSource\030\006 \001(\0162\036.entity.Eve" +
      "ntValue.EventSource\"b\n\tEventType\022\014\n\010Unde" +
      "fine\020\000\022\013\n\007Do_Like\020\001\022\r\n\tDo_Unlike\020\002\022\013\n\007Do" +
      "_Read\020\003\022\014\n\010Do_Reply\020\004\022\020\n\014Delete_Reply\020\005\"" +
      "+\n\013EventSource\022\010\n\004None\020\000\022\010\n\004Post\020\001\022\010\n\004Ch" +
      "at\020\002B\023\n\017tw.com.wd.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_entity_EventValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_entity_EventValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_entity_EventValue_descriptor,
        new String[] { "Value", "EventTimestamp", "ReceiverId", "GiverId", "EventType", "EventSource", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
