// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventValue.proto

package com.mitake.o.service.statistic.protobuf;

public final class EventValueOuterClass {
  private EventValueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:entity.EventValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 value = 1;</code>
     * @return The value.
     */
    int getValue();

    /**
     * <code>int64 eventTimestamp = 2;</code>
     * @return The eventTimestamp.
     */
    long getEventTimestamp();

    /**
     * <code>string receiverId = 3;</code>
     * @return The receiverId.
     */
    java.lang.String getReceiverId();
    /**
     * <code>string receiverId = 3;</code>
     * @return The bytes for receiverId.
     */
    com.google.protobuf.ByteString
        getReceiverIdBytes();

    /**
     * <code>string giverId = 4;</code>
     * @return The giverId.
     */
    java.lang.String getGiverId();
    /**
     * <code>string giverId = 4;</code>
     * @return The bytes for giverId.
     */
    com.google.protobuf.ByteString
        getGiverIdBytes();

    /**
     * <code>.entity.EventValue.EventType eventType = 5;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    int getEventTypeValue();
    /**
     * <code>.entity.EventValue.EventType eventType = 5;</code>
     * @return The eventType.
     */
    com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType getEventType();

    /**
     * <code>.entity.EventValue.EventSource eventSource = 6;</code>
     * @return The enum numeric value on the wire for eventSource.
     */
    int getEventSourceValue();
    /**
     * <code>.entity.EventValue.EventSource eventSource = 6;</code>
     * @return The eventSource.
     */
    com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource getEventSource();
  }
  /**
   * Protobuf type {@code entity.EventValue}
   */
  public static final class EventValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:entity.EventValue)
      EventValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventValue.newBuilder() to construct.
    private EventValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventValue() {
      receiverId_ = "";
      giverId_ = "";
      eventType_ = 0;
      eventSource_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventValue();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              value_ = input.readInt32();
              break;
            }
            case 16: {

              eventTimestamp_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              giverId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              eventType_ = rawValue;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              eventSource_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.internal_static_entity_EventValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.internal_static_entity_EventValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.class, com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.Builder.class);
    }

    /**
     * Protobuf enum {@code entity.EventValue.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Undefine = 0;</code>
       */
      Undefine(0),
      /**
       * <code>Do_Like = 1;</code>
       */
      Do_Like(1),
      /**
       * <code>Do_Unlike = 2;</code>
       */
      Do_Unlike(2),
      /**
       * <code>Do_Read = 3;</code>
       */
      Do_Read(3),
      /**
       * <code>Do_Reply = 4;</code>
       */
      Do_Reply(4),
      /**
       * <code>Delete_Reply = 5;</code>
       */
      Delete_Reply(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Undefine = 0;</code>
       */
      public static final int Undefine_VALUE = 0;
      /**
       * <code>Do_Like = 1;</code>
       */
      public static final int Do_Like_VALUE = 1;
      /**
       * <code>Do_Unlike = 2;</code>
       */
      public static final int Do_Unlike_VALUE = 2;
      /**
       * <code>Do_Read = 3;</code>
       */
      public static final int Do_Read_VALUE = 3;
      /**
       * <code>Do_Reply = 4;</code>
       */
      public static final int Do_Reply_VALUE = 4;
      /**
       * <code>Delete_Reply = 5;</code>
       */
      public static final int Delete_Reply_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EventType forNumber(int value) {
        switch (value) {
          case 0: return Undefine;
          case 1: return Do_Like;
          case 2: return Do_Unlike;
          case 3: return Do_Read;
          case 4: return Do_Reply;
          case 5: return Delete_Reply;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EventType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EventType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:entity.EventValue.EventType)
    }

    /**
     * Protobuf enum {@code entity.EventValue.EventSource}
     */
    public enum EventSource
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>None = 0;</code>
       */
      None(0),
      /**
       * <code>Post = 1;</code>
       */
      Post(1),
      /**
       * <code>Chat = 2;</code>
       */
      Chat(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>None = 0;</code>
       */
      public static final int None_VALUE = 0;
      /**
       * <code>Post = 1;</code>
       */
      public static final int Post_VALUE = 1;
      /**
       * <code>Chat = 2;</code>
       */
      public static final int Chat_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventSource valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EventSource forNumber(int value) {
        switch (value) {
          case 0: return None;
          case 1: return Post;
          case 2: return Chat;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventSource>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EventSource> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventSource>() {
              public EventSource findValueByNumber(int number) {
                return EventSource.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.getDescriptor().getEnumTypes().get(1);
      }

      private static final EventSource[] VALUES = values();

      public static EventSource valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EventSource(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:entity.EventValue.EventSource)
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>int32 value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }

    public static final int EVENTTIMESTAMP_FIELD_NUMBER = 2;
    private long eventTimestamp_;
    /**
     * <code>int64 eventTimestamp = 2;</code>
     * @return The eventTimestamp.
     */
    @java.lang.Override
    public long getEventTimestamp() {
      return eventTimestamp_;
    }

    public static final int RECEIVERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object receiverId_;
    /**
     * <code>string receiverId = 3;</code>
     * @return The receiverId.
     */
    @java.lang.Override
    public java.lang.String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverId_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverId = 3;</code>
     * @return The bytes for receiverId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIVERID_FIELD_NUMBER = 4;
    private volatile java.lang.Object giverId_;
    /**
     * <code>string giverId = 4;</code>
     * @return The giverId.
     */
    @java.lang.Override
    public java.lang.String getGiverId() {
      java.lang.Object ref = giverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        giverId_ = s;
        return s;
      }
    }
    /**
     * <code>string giverId = 4;</code>
     * @return The bytes for giverId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGiverIdBytes() {
      java.lang.Object ref = giverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        giverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 5;
    private int eventType_;
    /**
     * <code>.entity.EventValue.EventType eventType = 5;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.entity.EventValue.EventType eventType = 5;</code>
     * @return The eventType.
     */
    @java.lang.Override public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType getEventType() {
      @SuppressWarnings("deprecation")
      com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType result = com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType.valueOf(eventType_);
      return result == null ? com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType.UNRECOGNIZED : result;
    }

    public static final int EVENTSOURCE_FIELD_NUMBER = 6;
    private int eventSource_;
    /**
     * <code>.entity.EventValue.EventSource eventSource = 6;</code>
     * @return The enum numeric value on the wire for eventSource.
     */
    @java.lang.Override public int getEventSourceValue() {
      return eventSource_;
    }
    /**
     * <code>.entity.EventValue.EventSource eventSource = 6;</code>
     * @return The eventSource.
     */
    @java.lang.Override public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource getEventSource() {
      @SuppressWarnings("deprecation")
      com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource result = com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource.valueOf(eventSource_);
      return result == null ? com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0) {
        output.writeInt32(1, value_);
      }
      if (eventTimestamp_ != 0L) {
        output.writeInt64(2, eventTimestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiverId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiverId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(giverId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, giverId_);
      }
      if (eventType_ != com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType.Undefine.getNumber()) {
        output.writeEnum(5, eventType_);
      }
      if (eventSource_ != com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource.None.getNumber()) {
        output.writeEnum(6, eventSource_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      if (eventTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, eventTimestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiverId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiverId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(giverId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, giverId_);
      }
      if (eventType_ != com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType.Undefine.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, eventType_);
      }
      if (eventSource_ != com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource.None.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, eventSource_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue)) {
        return super.equals(obj);
      }
      com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue other = (com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue) obj;

      if (getValue()
          != other.getValue()) return false;
      if (getEventTimestamp()
          != other.getEventTimestamp()) return false;
      if (!getReceiverId()
          .equals(other.getReceiverId())) return false;
      if (!getGiverId()
          .equals(other.getGiverId())) return false;
      if (eventType_ != other.eventType_) return false;
      if (eventSource_ != other.eventSource_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (37 * hash) + EVENTTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEventTimestamp());
      hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverId().hashCode();
      hash = (37 * hash) + GIVERID_FIELD_NUMBER;
      hash = (53 * hash) + getGiverId().hashCode();
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
      hash = (37 * hash) + EVENTSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + eventSource_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code entity.EventValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:entity.EventValue)
        com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.internal_static_entity_EventValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.internal_static_entity_EventValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.class, com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.Builder.class);
      }

      // Construct using com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = 0;

        eventTimestamp_ = 0L;

        receiverId_ = "";

        giverId_ = "";

        eventType_ = 0;

        eventSource_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.internal_static_entity_EventValue_descriptor;
      }

      @java.lang.Override
      public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue getDefaultInstanceForType() {
        return com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.getDefaultInstance();
      }

      @java.lang.Override
      public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue build() {
        com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue buildPartial() {
        com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue result = new com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue(this);
        result.value_ = value_;
        result.eventTimestamp_ = eventTimestamp_;
        result.receiverId_ = receiverId_;
        result.giverId_ = giverId_;
        result.eventType_ = eventType_;
        result.eventSource_ = eventSource_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue) {
          return mergeFrom((com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue other) {
        if (other == com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        if (other.getEventTimestamp() != 0L) {
          setEventTimestamp(other.getEventTimestamp());
        }
        if (!other.getReceiverId().isEmpty()) {
          receiverId_ = other.receiverId_;
          onChanged();
        }
        if (!other.getGiverId().isEmpty()) {
          giverId_ = other.giverId_;
          onChanged();
        }
        if (other.eventType_ != 0) {
          setEventTypeValue(other.getEventTypeValue());
        }
        if (other.eventSource_ != 0) {
          setEventSourceValue(other.getEventSourceValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int value_ ;
      /**
       * <code>int32 value = 1;</code>
       * @return The value.
       */
      @java.lang.Override
      public int getValue() {
        return value_;
      }
      /**
       * <code>int32 value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }

      private long eventTimestamp_ ;
      /**
       * <code>int64 eventTimestamp = 2;</code>
       * @return The eventTimestamp.
       */
      @java.lang.Override
      public long getEventTimestamp() {
        return eventTimestamp_;
      }
      /**
       * <code>int64 eventTimestamp = 2;</code>
       * @param value The eventTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setEventTimestamp(long value) {
        
        eventTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 eventTimestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventTimestamp() {
        
        eventTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object receiverId_ = "";
      /**
       * <code>string receiverId = 3;</code>
       * @return The receiverId.
       */
      public java.lang.String getReceiverId() {
        java.lang.Object ref = receiverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverId = 3;</code>
       * @return The bytes for receiverId.
       */
      public com.google.protobuf.ByteString
          getReceiverIdBytes() {
        java.lang.Object ref = receiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverId = 3;</code>
       * @param value The receiverId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverId() {
        
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverId = 3;</code>
       * @param value The bytes for receiverId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object giverId_ = "";
      /**
       * <code>string giverId = 4;</code>
       * @return The giverId.
       */
      public java.lang.String getGiverId() {
        java.lang.Object ref = giverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          giverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string giverId = 4;</code>
       * @return The bytes for giverId.
       */
      public com.google.protobuf.ByteString
          getGiverIdBytes() {
        java.lang.Object ref = giverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          giverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string giverId = 4;</code>
       * @param value The giverId to set.
       * @return This builder for chaining.
       */
      public Builder setGiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        giverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string giverId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGiverId() {
        
        giverId_ = getDefaultInstance().getGiverId();
        onChanged();
        return this;
      }
      /**
       * <code>string giverId = 4;</code>
       * @param value The bytes for giverId to set.
       * @return This builder for chaining.
       */
      public Builder setGiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        giverId_ = value;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <code>.entity.EventValue.EventType eventType = 5;</code>
       * @return The enum numeric value on the wire for eventType.
       */
      @java.lang.Override public int getEventTypeValue() {
        return eventType_;
      }
      /**
       * <code>.entity.EventValue.EventType eventType = 5;</code>
       * @param value The enum numeric value on the wire for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventTypeValue(int value) {
        
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.entity.EventValue.EventType eventType = 5;</code>
       * @return The eventType.
       */
      @java.lang.Override
      public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType getEventType() {
        @SuppressWarnings("deprecation")
        com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType result = com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType.valueOf(eventType_);
        return result == null ? com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.entity.EventValue.EventType eventType = 5;</code>
       * @param value The eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.entity.EventValue.EventType eventType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        
        eventType_ = 0;
        onChanged();
        return this;
      }

      private int eventSource_ = 0;
      /**
       * <code>.entity.EventValue.EventSource eventSource = 6;</code>
       * @return The enum numeric value on the wire for eventSource.
       */
      @java.lang.Override public int getEventSourceValue() {
        return eventSource_;
      }
      /**
       * <code>.entity.EventValue.EventSource eventSource = 6;</code>
       * @param value The enum numeric value on the wire for eventSource to set.
       * @return This builder for chaining.
       */
      public Builder setEventSourceValue(int value) {
        
        eventSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.entity.EventValue.EventSource eventSource = 6;</code>
       * @return The eventSource.
       */
      @java.lang.Override
      public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource getEventSource() {
        @SuppressWarnings("deprecation")
        com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource result = com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource.valueOf(eventSource_);
        return result == null ? com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource.UNRECOGNIZED : result;
      }
      /**
       * <code>.entity.EventValue.EventSource eventSource = 6;</code>
       * @param value The eventSource to set.
       * @return This builder for chaining.
       */
      public Builder setEventSource(com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue.EventSource value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eventSource_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.entity.EventValue.EventSource eventSource = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventSource() {
        
        eventSource_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:entity.EventValue)
    }

    // @@protoc_insertion_point(class_scope:entity.EventValue)
    private static final com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue();
    }

    public static com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventValue>
        PARSER = new com.google.protobuf.AbstractParser<EventValue>() {
      @java.lang.Override
      public EventValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mitake.o.service.statistic.protobuf.EventValueOuterClass.EventValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_entity_EventValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_entity_EventValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020EventValue.proto\022\006entity\"\317\002\n\nEventValu" +
      "e\022\r\n\005value\030\001 \001(\005\022\026\n\016eventTimestamp\030\002 \001(\003" +
      "\022\022\n\nreceiverId\030\003 \001(\t\022\017\n\007giverId\030\004 \001(\t\022/\n" +
      "\teventType\030\005 \001(\0162\034.entity.EventValue.Eve" +
      "ntType\0223\n\013eventSource\030\006 \001(\0162\036.entity.Eve" +
      "ntValue.EventSource\"b\n\tEventType\022\014\n\010Unde" +
      "fine\020\000\022\013\n\007Do_Like\020\001\022\r\n\tDo_Unlike\020\002\022\013\n\007Do" +
      "_Read\020\003\022\014\n\010Do_Reply\020\004\022\020\n\014Delete_Reply\020\005\"" +
      "+\n\013EventSource\022\010\n\004None\020\000\022\010\n\004Post\020\001\022\010\n\004Ch" +
      "at\020\002B)\n\'com.mitake.o.service.statistic.p" +
      "rotobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_entity_EventValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_entity_EventValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_entity_EventValue_descriptor,
        new java.lang.String[] { "Value", "EventTimestamp", "ReceiverId", "GiverId", "EventType", "EventSource", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
